// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: budget.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budget (
  id,user_id,amount,start_date,valid,end_date,created_at,updated_at
) VALUES ( $1,$2,$3,$4,$5,$6,$7,$8 )
RETURNING id, user_id, amount, spent_amount, remaining_amount, spent_percentage, valid, start_date, end_date, created_at, updated_at
`

type CreateBudgetParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Amount    string    `json:"amount"`
	StartDate time.Time `json:"start_date"`
	Valid     bool      `json:"valid"`
	EndDate   time.Time `json:"end_date"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, createBudget,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.StartDate,
		arg.Valid,
		arg.EndDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.SpentAmount,
		&i.RemainingAmount,
		&i.SpentPercentage,
		&i.Valid,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :one
DELETE FROM budget
  WHERE id = $1 and user_id = $2
RETURNING id, user_id, amount, spent_amount, remaining_amount, spent_percentage, valid, start_date, end_date, created_at, updated_at
`

type DeleteBudgetParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, deleteBudget, arg.ID, arg.UserID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.SpentAmount,
		&i.RemainingAmount,
		&i.SpentPercentage,
		&i.Valid,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const makeBudgetInvalid = `-- name: MakeBudgetInvalid :one
UPDATE budget
  SET valid = FALSE
  WHERE id = $1 and user_id = $2
RETURNING id, user_id, amount, spent_amount, remaining_amount, spent_percentage, valid, start_date, end_date, created_at, updated_at
`

type MakeBudgetInvalidParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MakeBudgetInvalid(ctx context.Context, arg MakeBudgetInvalidParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, makeBudgetInvalid, arg.ID, arg.UserID)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.SpentAmount,
		&i.RemainingAmount,
		&i.SpentPercentage,
		&i.Valid,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budget
  SET amount = $3,spent_amount = $4, start_date = $5, end_date=$6,updated_at= $7 
  WHERE id = $1 and user_id = $2
RETURNING id, user_id, amount, spent_amount, remaining_amount, spent_percentage, valid, start_date, end_date, created_at, updated_at
`

type UpdateBudgetParams struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Amount      string    `json:"amount"`
	SpentAmount string    `json:"spent_amount"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, updateBudget,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.SpentAmount,
		arg.StartDate,
		arg.EndDate,
		arg.UpdatedAt,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.SpentAmount,
		&i.RemainingAmount,
		&i.SpentPercentage,
		&i.Valid,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
