// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Transaction struct {
	ID              uuid.UUID
	Amount          int64
	Description     sql.NullString
	Category        sql.NullString
	TransactionType string
	TransactionDate time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
