// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Budget struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Amount          string         `json:"amount"`
	SpentAmount     string         `json:"spent_amount"`
	RemainingAmount sql.NullString `json:"remaining_amount"`
	SpentPercentage sql.NullString `json:"spent_percentage"`
	Valid           bool           `json:"valid"`
	StartDate       time.Time      `json:"start_date"`
	EndDate         time.Time      `json:"end_date"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Category struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Transaction struct {
	ID              uuid.UUID      `json:"id"`
	Amount          string         `json:"amount"`
	Description     sql.NullString `json:"description"`
	CategoriesID    uuid.UUID      `json:"categories_id"`
	UserID          uuid.UUID      `json:"user_id"`
	TransactionType string         `json:"transaction_type"`
	TransactionDate time.Time      `json:"transaction_date"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	Password     string         `json:"password"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	Token        sql.NullString `json:"token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	Role         string         `json:"role"`
}
