// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: transactions.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addTransactions = `-- name: AddTransactions :one
INSERT INTO transactions (
  id,amount,description,transaction_type,categories_id,user_id,transaction_date,created_at, updated_at
) VALUES ( $1,$2,$3,$4, $5,$6,$7,$8,$9)
RETURNING id, amount, description, categories_id, user_id, transaction_type, transaction_date, created_at, updated_at
`

type AddTransactionsParams struct {
	ID              uuid.UUID      `json:"id"`
	Amount          string         `json:"amount"`
	Description     sql.NullString `json:"description"`
	TransactionType string         `json:"transaction_type"`
	CategoriesID    uuid.UUID      `json:"categories_id"`
	UserID          uuid.UUID      `json:"user_id"`
	TransactionDate time.Time      `json:"transaction_date"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) AddTransactions(ctx context.Context, arg AddTransactionsParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, addTransactions,
		arg.ID,
		arg.Amount,
		arg.Description,
		arg.TransactionType,
		arg.CategoriesID,
		arg.UserID,
		arg.TransactionDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Description,
		&i.CategoriesID,
		&i.UserID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTransactionById = `-- name: DeleteTransactionById :one
DELETE FROM transactions
WHERE id =$1 and user_id = $2
RETURNING id, amount, description, categories_id, user_id, transaction_type, transaction_date, created_at, updated_at
`

type DeleteTransactionByIdParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteTransactionById(ctx context.Context, arg DeleteTransactionByIdParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, deleteTransactionById, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Description,
		&i.CategoriesID,
		&i.UserID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllTransactions = `-- name: GetAllTransactions :many
SELECT id, amount,transaction_type,description,categories_id,user_id,transaction_date,created_at, updated_at FROM transactions
WHERE user_id = $1
`

type GetAllTransactionsRow struct {
	ID              uuid.UUID      `json:"id"`
	Amount          string         `json:"amount"`
	TransactionType string         `json:"transaction_type"`
	Description     sql.NullString `json:"description"`
	CategoriesID    uuid.UUID      `json:"categories_id"`
	UserID          uuid.UUID      `json:"user_id"`
	TransactionDate time.Time      `json:"transaction_date"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) GetAllTransactions(ctx context.Context, userID uuid.UUID) ([]GetAllTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTransactionsRow
	for rows.Next() {
		var i GetAllTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.TransactionType,
			&i.Description,
			&i.CategoriesID,
			&i.UserID,
			&i.TransactionDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionById = `-- name: GetTransactionById :one
SELECT id, amount, description, categories_id, user_id, transaction_type, transaction_date, created_at, updated_at FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionById(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransactionById, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Description,
		&i.CategoriesID,
		&i.UserID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
  SET amount = $3, description = $4,transaction_type = $5, categories_id = $6,updated_at = $7
  WHERE id = $1 and user_id=$2
RETURNING id, amount, description, categories_id, user_id, transaction_type, transaction_date, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Amount          string         `json:"amount"`
	Description     sql.NullString `json:"description"`
	TransactionType string         `json:"transaction_type"`
	CategoriesID    uuid.UUID      `json:"categories_id"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.ID,
		arg.UserID,
		arg.Amount,
		arg.Description,
		arg.TransactionType,
		arg.CategoriesID,
		arg.UpdatedAt,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Description,
		&i.CategoriesID,
		&i.UserID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
