// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS (
    SELECT 1 FROM users 
    WHERE email = $1 OR username = $2
)
`

type CheckUserExistsParams struct {
	Email    string `json:"email"`
	Username string `json:"username"`
}

func (q *Queries) CheckUserExists(ctx context.Context, arg CheckUserExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkUserExists, arg.Email, arg.Username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
  id,username,email,password,first_name,last_name,role,created_at,updated_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) 
RETURNING id, username, email, password, first_name, last_name, created_at, updated_at, token, refresh_token, role
`

type CreateUserParams struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT refresh_token FROM users WHERE id = $1
`

func (q *Queries) GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getRefreshTokenByID, id)
	var refresh_token sql.NullString
	err := row.Scan(&refresh_token)
	return refresh_token, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, first_name, last_name, created_at, updated_at, token, refresh_token, role FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.RefreshToken,
		&i.Role,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password, first_name, last_name, created_at, updated_at, token, refresh_token, role FROM users WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.RefreshToken,
		&i.Role,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, first_name, last_name, created_at, updated_at, token, refresh_token, role FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.RefreshToken,
		&i.Role,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
SELECT id, username, email, password, first_name, last_name, created_at, updated_at, token, refresh_token, role FROM users WHERE username = $1 OR email = $2
`

type GetUserByUsernameOrEmailParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameOrEmail, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.RefreshToken,
		&i.Role,
	)
	return i, err
}

const updateUserTokens = `-- name: UpdateUserTokens :one
UPDATE users
  SET token = $2, refresh_token= $3, updated_at = $4
  WHERE id = $1
RETURNING id, username, email, password, first_name, last_name, created_at, updated_at, token, refresh_token, role
`

type UpdateUserTokensParams struct {
	ID           uuid.UUID      `json:"id"`
	Token        sql.NullString `json:"token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) UpdateUserTokens(ctx context.Context, arg UpdateUserTokensParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserTokens,
		arg.ID,
		arg.Token,
		arg.RefreshToken,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Token,
		&i.RefreshToken,
		&i.Role,
	)
	return i, err
}
