name: test actions

on: 
  push:
    branches : [main]
  pull_request:
    branches: [main]

#what to run
jobs: 
  test:
    #first thing is to specify the operating system
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x' #can ignore this
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.text ]; then pip install -r requirements.txt; fi
      
      - name: Run Pytest
        run: pytest
